# Generated by Django 3.2.12 on 2022-04-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20220412_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp513', max_length=70),
        ),
    ]
