# Generated by Django 3.2.12 on 2022-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_auto_20220413_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp366', max_length=70),
        ),
    ]
