# Generated by Django 3.2.12 on 2022-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20220422_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_purpose',
            field=models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('MEDICAL', 'MEDICAL'), ('OTHERS', 'OTHERS')], default='ANNUAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp929', max_length=70),
        ),
    ]
