# Generated by Django 3.2.12 on 2022-04-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_auto_20220422_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp768', max_length=70),
        ),
        migrations.CreateModel(
            name='NexxtOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('Relationship1', models.CharField(max_length=255)),
                ('phone_number1', models.IntegerField()),
                ('name2', models.CharField(max_length=255)),
                ('Relationship2', models.CharField(max_length=255)),
                ('phone_number2', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.employee')),
            ],
        ),
    ]
