# Generated by Django 3.2.12 on 2022-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_auto_20220422_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NexxtOfKin',
            new_name='NextOfKin',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp864', max_length=70),
        ),
    ]
