# Generated by Django 3.2.12 on 2022-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_auto_20220422_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='Relationship1',
            new_name='relationship1',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='Relationship2',
            new_name='relationship2',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp705', max_length=70),
        ),
    ]
