# Generated by Django 3.2.12 on 2022-04-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_auto_20220422_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp997', max_length=70),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.employee'),
        ),
    ]
