# Generated by Django 3.2.12 on 2022-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0021_auto_20220423_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp128', max_length=70),
        ),
    ]
