# Generated by Django 3.2.12 on 2022-04-24 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0022_auto_20220424_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp332', max_length=70),
        ),
    ]
