# Generated by Django 3.2.12 on 2022-04-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0023_auto_20220424_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='director',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp762', max_length=70),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.CharField(default='emp332', max_length=70)),
                ('address', models.TextField(default='', max_length=1000)),
                ('local_government', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('date_of_first_appointment', models.DateField()),
                ('date_of_present_appointment', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('grade_level', models.IntegerField()),
                ('emergency', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('yoruba', 'YORUBA'), ('hausa', 'HAUSA'), ('igbo', 'IGBO')], default='english', max_length=10)),
                ('nuban', models.CharField(blank=True, max_length=10)),
                ('bank', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=16)),
                ('retirement_date_by_age', models.DateField()),
                ('retirement_date_by_years_of_service', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
