# Generated by Django 3.2.12 on 2022-04-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0028_auto_20220426_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED')], default='MARRIED', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='religion',
            field=models.CharField(choices=[('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM'), ('OTHER', 'OTHER')], default='CHRISTIAN', max_length=255),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.CharField(default='dir691', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp174', max_length=70),
        ),
    ]
