# Generated by Django 3.2.12 on 2022-04-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0030_auto_20220427_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.CharField(default='dir938', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp892', max_length=70),
        ),
        migrations.CreateModel(
            name='DirectorNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('relationship1', models.CharField(max_length=255)),
                ('phone_number1', models.IntegerField()),
                ('name2', models.CharField(max_length=255)),
                ('relationship2', models.CharField(max_length=255)),
                ('phone_number2', models.IntegerField()),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.director')),
            ],
        ),
    ]
