# Generated by Django 3.2.12 on 2022-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0033_auto_20220427_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='last_out',
        ),
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.CharField(default='dir341', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp434', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
